@tool
extends EditorPlugin

# 这个插件用于自动绑定当前场景中，特定前缀的节点，避免手动声明@onready变量和手动拖拽节点
# 节约了手写@onready声明、拖动节点、维护节点路径的成本
# 可以在NODE_TYPE中自定义前缀和静态类型

# 点击：项目-工具-Generate Node Bindings
# 生成的代码形如：
# # Autogenerated Bindings Start
# @onready var img_robot: TextureRect = $MarginContainer/BoxContainer/RobotDesc/MarginContainer/BoxContainer/Img_Robot
# @onready var txt_robot: Label = $MarginContainer/BoxContainer/RobotDesc/MarginContainer/BoxContainer/Txt_Robot
# # Autogenerated Bindings End

# 代码生成于场景根节点的脚本中，并以节点名为变量名
# 后续若修改节点名称，必须在该脚本中替换全文中的变量名
# 因此，禁止外部代码直接使用这些变量，如必须，可在该脚本中提供接口

# 插件名称
const NAME: String = "Generate Node Bindings"

# 自动生成代码的开始和结束标记
const START: String = "# Autogenerated Bindings Start"
const END: String = "# Autogenerated Bindings End"

# 节点名前缀与对应类型的映射
const NODE_TYPE: Dictionary = {
	"Img_": "TextureRect",
	"Txt_": "Label",
}

# 插件入口，在插件加载时调用
func _enter_tree() -> void:
	# 将自定义工具加入到 Godot 编辑器的工具菜单
	add_tool_menu_item(NAME, _on_generate_bindings)

# 插件卸载时调用
func _exit_tree() -> void:
	# 从 Godot 编辑器中移除自定义工具
	remove_tool_menu_item(NAME)


# 生成绑定代码的按钮回调函数
func _on_generate_bindings() -> void:
	# 获取当前编辑的场景根节点
	var scene_root: Node = get_editor_interface().get_edited_scene_root()

	# 确保场景根节点存在
	if scene_root:
		# 获取根节点的脚本路径
		var script_path: String = scene_root.get_script().resource_path
		if script_path != "":
			# 生成节点绑定代码
			var bindings: Array[String] = generate_component_bindings(scene_root)
			# 将绑定代码写入脚本文件
			write_bindings_to_script(script_path, bindings)
			# 重新加载脚本
			scene_root.get_script().reload()
		else:
			# 如果根节点没有附加脚本，则报错
			push_error("No script attached to the root node!")
	else:
		# 如果没有场景处于编辑状态，则报错
		push_error("No scene is currently open in the editor!")

# 遍历当前场景并生成绑定代码
# `root`: 根节点，`cur`: 当前处理的节点（递归）
func generate_component_bindings(root: Node, cur: Node = root) -> Array[String]:
	var bindings: Array[String] = []

	# 遍历当前节点的所有子节点
	for child in cur.get_children():
		# 根据节点名称的前缀匹配类型
		for t in NODE_TYPE:
			if child.name.begins_with(t):
				# 生成绑定代码行
				bindings.append("@onready var %s: %s = $%s" % [child.name.to_lower(), NODE_TYPE[t], root.get_path_to(child)])
				break

		# 递归处理子节点
		bindings.append_array(generate_component_bindings(root, child))

	return bindings

# 将生成的绑定代码写入脚本
# `script_path`: 脚本文件路径, `bindings`: 生成的绑定代码
func write_bindings_to_script(script_path: String, bindings: Array[String]) -> void:
	# 打开脚本文件以进行读写操作
	var file: FileAccess = FileAccess.open(script_path, FileAccess.READ_WRITE)

	if file:
		# 读取脚本的内容
		var content: String = file.get_as_text()
		
		# 查找自动生成代码的开始和结束标记
		var start_idx: int = content.find(START)
		var end_idx: int = content.find(END)
		
		if start_idx != -1 and end_idx != -1:
			# 删除旧的绑定代码，保留开始和结束标记
			var before_bindings: String = content.substr(0, start_idx + START.length())
			var after_bindings: String = content.substr(end_idx)
			
			# 插入新的绑定代码
			var new_bindings: String = "\n"
			for binding in bindings:
				new_bindings += binding + "\n"
			
			# 替换旧的绑定代码
			content = before_bindings + new_bindings + after_bindings
		else:
			# 如果没有找到标记，则添加标记和新的绑定代码
			var new_bindings: String = START + "\n"
			for binding in bindings:
				new_bindings += binding + "\n"
			new_bindings += END + "\n"
			content += "\n" + new_bindings
		
		# 重置文件指针并写入新的内容
		file.seek(0)
		file.store_string(content)
		file.close()
		
		# 输出成功写入的信息
		print("Bindings successfully written to script: ", script_path)
	else:
		# 如果文件无法打开，则报错
		push_error("Failed to open script file: ", script_path)
