
extends PanelContainer


# Autogenerated Bindings Start
@onready var img_robot: TextureRect = $MarginContainer/BoxContainer/RobotDesc/MarginContainer/BoxContainer/Img_Robot
@onready var txt_robot: Label = $MarginContainer/BoxContainer/RobotDesc/MarginContainer/BoxContainer/Txt_Robot
# Autogenerated Bindings End
